export const specializationsContent = {
  title: "Minhas Especializações",
  items: [
    "PSICOLOGIA INFANTIL – ATUAÇÃO NO DESENVOLVIMENTO EMOCIONAL E COMPORTAMENTAL DAS CRIANÇAS, AUXILIANDO TAMBÉM OS PAIS NO PROCESSO DE EDUCAÇÃO EMOCIONAL.",
    "PSICOLOGIA PERINATAL – SUPORTE EMOCIONAL PARA GESTANTES, PUÉRPERAS E PARA AQUELES QUE DESEJAM TER UM(A) FILHO(A) DO CORAÇÃO, AUXILIANDO FUTUROS PAIS E MÃES QUE ESTÃO NA FILA DA ADOÇÃO. O ACOMPANHAMENTO AJUDA NO PREPARO PARA A PARENTALIDADE E NAS TRANSFORMAÇÕES EMOCIONAIS DESSE PERÍODO.",
    "COACHING PSICOLÓGICO – DESENVOLVIMENTO PESSOAL E PROFISSIONAL COM TÉCNICAS BASEADAS NA PSICOLOGIA E NO AUTOCONHECIMENTO.",
    "ANÁLISE COMPORTAMENTAL – IDENTIFICAÇÃO DE PADRÕES DE COMPORTAMENTO E ESTRATÉGIAS PARA PROMOVER MUDANÇAS SAUDÁVEIS.",
  ],
};
